# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: "Paco Orozco"
title: "Paco Orozco"
#description: "Engineering Manager at Adevinta focalizado en el diseño de servicios a escala global: media delivery services and GDPR compliance."
#logo: 'assets/images/logo.png'
#favicon: 'assets/images/logo.png'
baseurl: "" # the subpath of your site, e.g. /blog
#include: ["_pages"]
permalink: /:slug

# Build settings
theme: mediumish

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Authors
authors:
  paco:
    name: Paco Orozco
    display_name: Paco
    avatar: assets/img/PacoOrozco_Adevinta_640.jpg
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: paco@pacoorozco.info
    web: https://pacoorozco.info
    twitter: https://twitter.com/pakusland
    description: "Engineering Manager at Adevinta focalizado en el diseño de servicios a escala global: media delivery services and GDPR compliance."

# Pagination 
paginate: 6
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

